module.exports = {
  RED: 'red',
  BLACK: 'black',
  TOTAL_MEMTABLE_NODES_ACCEPTABLE: 2 * Math.pow(10, 6),
  SM_TABLE_MAX_SIZE_IN_BYTES: 1000000,
  SM_TABLE_IN_MEMORY_SPARSE_KEYS_THRESHOLD_BYTES: 1000
};